title: Raghavi Rajumohan
logo: images/Raghavi.jpg
description: # your text below (remove <br> elements if you don't need line breaks)
  I love uncovering insights from data and turning those stories into actionable insights.
<br><br>

## Experiences

<ul class="timeline">
  <li>
    <span>Sep 2024 - Present</span> 
    <strong>Founder & Mentor</strong> - Data Gals Initiative
  </li>
  <li>
    <span>Jun 2024 - Present</span>
    <strong>Data Science Intern, Real Estate Practice</strong> - ABGi USA
  </li>
  <li>
    <span>Jan 2024 - Mar 2024</span>
    <strong>Quantitative Analyst</strong> - Optimas Capital
  </li>
  <li>
    <span>Aug 2023 - Sep 2023</span>
    <strong>Data Analyst</strong> - Equity Methods LLC
  </li>
</ul>

## Connect with Me

<ul>
  <li><a href="https://www.linkedin.com/in/raghavi-rajumohan/">View My LinkedIn</a></li>
  <li><a href="https://github.com/RaghaviRajumohan">Visit My GitHub</a></li>
</ul>

<style>
/* Add styling for the timeline */
ul.timeline {
  list-style-type: none;
  position: relative;
}
ul.timeline:before {
  content: '';
  background: #d4d9df;
  display: inline-block;
  position: absolute;
  left: 20px;
  width: 2px;
  height: 100%;
  z-index: 400;
}
ul.timeline > li {
  margin: 20px 0;
  padding-left: 40px;
}
ul.timeline > li:before {
  content: '';
  background: #6e8cd4;
  display: inline-block;
  position: absolute;
  border-radius: 50%;
  left: 15px;
  width: 12px;
  height: 12px;
  z-index: 400;
}
</style>

theme: jekyll-theme-minimal

