# Title and Description
title: "Raghavi Rajumohan"
description: "I love uncovering insights from data and turning those stories into actionable insights."

# Timeline Experiences
experiences: > 
  <div style="position: relative; max-width: 800px; margin: 0 auto; padding: 10px 0;">
    <!-- Experience 1 -->
    <div style="padding: 10px 0; position: relative;">
      <div style="font-weight: bold; color: #b19cd9; float: left; width: 30%; text-align: right; padding-right: 15px; font-size: 0.9em;">
        Sep 2024 - Present
      </div>
      <div style="padding-left: 35px; border-left: 2px solid #b19cd9; position: relative;">
        <h3>Founder & Mentor - Data Gals Initiative</h3>
      </div>
    </div>

    <!-- Experience 2 -->
    <div style="padding: 10px 0; position: relative;">
      <div style="font-weight: bold; color: #b19cd9; float: left; width: 30%; text-align: right; padding-right: 15px; font-size: 0.9em;">
        Jun 2024 - Present
      </div>
      <div style="padding-left: 35px; border-left: 2px solid #b19cd9; position: relative;">
        <h3>Data Science Intern, Real Estate Practice - ABGi USA</h3>
      </div>
    </div>

    <!-- Experience 3 -->
    <div style="padding: 10px 0; position: relative;">
      <div style="font-weight: bold; color: #b19cd9; float: left; width: 30%; text-align: right; padding-right: 15px; font-size: 0.9em;">
        Jan 2024 - Mar 2024
      </div>
      <div style="padding-left: 35px; border-left: 2px solid #b19cd9; position: relative;">
        <h3>Quantitative Analyst - Optimas Capital</h3>
      </div>
    </div>

    <!-- Experience 4 -->
    <div style="padding: 10px 0; position: relative;">
      <div style="font-weight: bold; color: #b19cd9; float: left; width: 30%; text-align: right; padding-right: 15px; font-size: 0.9em;">
        Aug 2023 - Sep 2023
      </div>
      <div style="padding-left: 35px; border-left: 2px solid #b19cd9; position: relative;">
        <h3>Data Analyst - Equity Methods LLC</h3>
      </div>
    </div>
  </div>

# Social Links
social_links: > 
  <a href="https://www.linkedin.com/in/raghavi-rajumohan/" target="_blank" style="color:#6a0dad;">
    <img src="images/LinkedIn_icon.svg.png" alt="LinkedIn" style="width:50px;height:40px;margin-right:5px;">
    View My LinkedIn
  </a>
  <br><br>
  <a href="https://github.com/RaghaviRajumohan" target="_blank" style="color:#6a0dad;">
    <img src="images/Github_icon.png" alt="GitHub" style="width:50px;height:40px;margin-right:5px;">
    Visit My GitHub
  </a>
