title: "Raghavi Rajumohan | Data Scientist Portfolio"
logo: "images/logo.png"  # Add your logo image here
description: "I love uncovering insights from data and turning those stories into actionable insights."

experiences:
  - date: "Sep 2024 - Present"
    title: "Founder & Mentor - Data Gals Initiative"
    description: "Leading a community of women in data science, fostering growth and mentoring aspiring data scientists."

  - date: "Jun 2024 - Present"
    title: "Data Science Intern - Real Estate Practice, ABGi USA"
    description: "Conducting market analysis using data-driven techniques to identify trends in real estate investments."

  - date: "Jan 2024 - Mar 2024"
    title: "Quantitative Analyst - Optimas Capital"
    description: "Analyzed financial datasets and developed models to assist in high-stakes financial decision-making."

  - date: "Aug 2023 - Sep 2023"
    title: "Data Analyst - Equity Methods LLC"
    description: "Worked with equity valuation models, providing actionable insights on company performance metrics."
