title: "Raghavi Rajumohan"
logo: "/images/logo.png?raw=true"  # Your photo (or logo) here
description: >
  I love uncovering insights from data and turning those stories into actionable insights.
  <br><br>

  <!-- Experiences Section -->
  <strong>Experiences:</strong>
  <ul style="list-style-type: disc; padding-left: 20px; max-width: 800px; margin: 0 auto;">
    <li><strong>Jul 2024 - Present</strong> Data Metrics Analyst Intern - University of California, Office of the President</li>
    <li><strong>Jan 2024 - May 2024</strong> Data Analyst and Project Mentor - UCLA Alumni Affairs</li>
    <li><strong>Sep 2020 - Jul 2023</strong> Data Analysis General Manager - WageIndicator Foundation Research Lab</li>
    <li><strong>May 2021 - Jul 2022</strong> Business Development Intern - TATA Electronics Pvt. Ltd.</li>
  </ul>
  <br><br>

  <!-- Social Links Section -->
  <strong>Connect with Me:</strong>
  <ul style="list-style-type: none; padding-left: 0;">
    <li>
      <a href="https://www.linkedin.com/in/raghavirajumohan/" style="color:#6a0dad;">
        <img src="images/LinkedIn_icon.svg.png" alt="LinkedIn" style="width:50px;height:40px;margin-right:5px;">
        LinkedIn
      </a>
    </li>
    <li>
      <a href="https://github.com/RaghaviRajumohan" style="color:#6a0dad;">
        <img src="images/Github_icon.png" alt="GitHub" style="width:50px;height:40px;margin-right:5px;">
        GitHub
      </a>
    </li>
  </ul>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
